/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aion.main.presentation.generic.experience;

import aion.main.core.Experience;
import aion.main.core.environment.Position;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.BoxLayout;

/**
 *
 * @author Fanaen
 */
public class GenericExperiencePanel extends javax.swing.JPanel
{
    // -- Attributes --
    private ProgressPanel subjectPanel;
    private PositionPanel positionPanel;
    private ActionPanel actionPanel;
    private Experience experience;
    
    /**
     * Creates new form GenericExperiencePanel
     */
    public GenericExperiencePanel(Experience experience)
    {
        this.experience = experience;
        subjectPanel = new ProgressPanel(experience);
        positionPanel = new PositionPanel(experience);
        actionPanel = new ActionPanel(experience, this);
        
        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(subjectPanel);
        add(positionPanel);
        add(actionPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void moveToPosition(Position position) {
        positionPanel.moveToPosition(position);
    }
}
